services:
  go:
    build:
      context: .
      target: source
    environment:
      CGO_ENABLED: "0"
    volumes:
      - .:/src

  app-pvm:
    build:
      context: .
      target: runtime
    entrypoint: ["sleep", "infinity"]
    working_dir: /app
    volumes:
      - .:/app:ro
      - ./.local/apt/archives:/var/cache/apt/archives
    init: true
