//go:build linux || darwin

package symlink

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// EnsureShim (re)writes the php shim script in ShimDir(base).
func EnsureShim(base string) error {
	exe, err := os.Executable()
	if err != nil {
		return fmt.Errorf("locate pvm executable: %w", err)
	}
	if resolved, err := filepath.EvalSymlinks(exe); err == nil {
		exe = resolved
	}
	return writeShim(filepath.Join(ShimDir(base), "php"), exe)
}

// shimScript delegates to `pvm shim php`, which picks the version for the
// current directory ($PVM_VERSION, .php-version, then the global version).
func shimScript(pvmExe string) string {
	return "#!/bin/sh\n" +
		"# Managed by pvm — do not edit. Regenerated by `pvm use` and `pvm local`.\n" +
		"exec " + shellQuote(pvmExe) + " shim php \"$@\"\n"
}

func writeShim(path, pvmExe string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	os.Remove(tmp)
	if err := os.WriteFile(tmp, []byte(shimScript(pvmExe)), 0755); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
